version: '3.4'

services:
  edutest:
    image: edutest-img
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
